SpendOMeter/Models/HomeViewModel.cs
namespace SpendOMeter.ViewModels
{
    public class HomeViewModel
    {
        public string Client { get; set; }
    }
}

SpendOMeter/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using SpendOMeter.ViewModels;
using SomRepositories;
using SpendOMeter.Domain;

namespace SpendOMeter.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.Title = "Home Page";
            string clientDesc = "?";
            if(Request.Browser.IsMobileDevice)
            {
                clientDesc = "Mobile";
            }
            HomeViewModel viewModel = new HomeViewModel()
            {
                Client = clientDesc
            };
            return View(viewModel);
        }


        public ActionResult BudgetChartView()
        {
            ChartViewModel viewModel = new ChartViewModel()
            {
                Chart = BuildChart()
            };

            return View(viewModel);
        }
        

        private System.Web.Helpers.Chart BuildChart()
        {
            UsersRepository repository = new UsersRepository();
            BudgetSummary budgetSummary = repository.GetBudgetSummary(1);

            System.Web.Helpers.Chart chart = new System.Web.Helpers.Chart(400, 500, ChartTheme.Green)
             .AddTitle($"My Budget: ${budgetSummary.Amount}")
              //.AddLegend("Item1")
              .AddSeries
             (
                 chartType: "StackedColumn",
                    name: $"Spent: ${budgetSummary.Spent}",
                 xValue: new[] { "August, 2016" },
                 yValues: new[] { budgetSummary.Spent },
                 axisLabel: $"Spent {budgetSummary.Spent}"
             )
             .AddSeries(
             chartType: "StackedColumn",
             name: $"Remaining: ${budgetSummary.Remaining}",
             xValue: new[] { "August, 2016" },
             yValues: new[] { budgetSummary.Remaining },
             axisLabel: $"Remaining: ${budgetSummary.Remaining}"
             )
             .AddLegend();

            return chart;
            //    .AddSeries(chartType: "StackedBar",
            //        xValue: new[] { "2012", "2013", "2014", "2015" },
            //        yValues: new[] { 15, 5, 74, 32 }

            //)
            //.AddLegend()
            //.AddSeries(
            ////name: "WebSite",
            //chartType: "column",
            //xValue: new[] { "Digg", "DZone", "DotNetKicks", "StumbleUpon" },
            //yValues: new[] { "150000", "180000", "120000", "250000" })
            
            //return new System.Web.Helpers.Chart(600, 400, ChartTheme.Blue)
            //    .AddTitle("Number of website readers")
            //    .AddLegend()
            //    .AddSeries(
            //        name: "WebSite",
            //        chartType: "column",
            //        xValue: new[] { "Digg", "DZone", "DotNetKicks", "StumbleUpon" },
            //        yValues: new[] { "150000", "180000", "120000", "250000" });

        }
    }
}

SpendOMeter/Controllers/PaymentsController.cs
using SpendOMeter.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SpendOMeter.Domain;
using SpendOMeter.Repositories;

namespace SpendOMeter.Controllers
{
    public class PaymentsController : SkateBaseController
    {
        // GET: Payments
        public ActionResult Index()
        {
            PaymentsViewModel viewModel = new PaymentsViewModel();
            viewModel.Paymnets = GetPayments();
            return View(viewModel);
        }

        private IEnumerable<Payment> GetPayments()
        {
            PaymentsRepository repository = new PaymentsRepository();
            IEnumerable<Payment> payments = repository.Get();
            //List<PaymentViewModel> retVal = new List<PaymentViewModel>();
            //// Use AutoMapper
            //foreach(Payment payment in payments)
            //{

            //}
            //return retVal;
            return payments;
        }

        // GET: Payments/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Payments/Create
        public ActionResult Create()
        {
            if (Request.UrlReferrer != null)
            {
                ViewBag.ReferringUrl = Request.UrlReferrer.ToString();
            }
            RecipientsRepository repository = new RecipientsRepository();
            ViewBag.Recipients = repository.Get();
            Payment payment = new Payment();
            return View(payment);
        }

        // POST: Payments/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            DateTime date = DateTime.Now;
            decimal amount = new decimal(0.0);
            int recipientId = 0;
            string name = "";
            try
            {
                amount = GetFormValue<decimal>(collection, "amount");
                name = GetFormValue<string>(collection, "name");
                date = GetFormValue<DateTime>(collection, "date");
                recipientId = GetFormValue<int>(collection, "recipientId");
                PaymentsRepository repository = new PaymentsRepository();
                Payment payment = new Payment()
                {
                    Amount = amount,
                    Name = name,
                    Date = date,
                    RecipientId = recipientId,
                    CategoryId = 1
                };
                repository.Add(payment);
                //return SkateRedirect(collection);
                return RedirectToAction("Index");
            }
            catch(Exception ex)
            {
                throw new Exception("Failed to add payment.", ex);
                //return View();
            }
        }

        // GET: Payments/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Payments/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Payments/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Payments/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

SpendOMeter/Views/Home/BudgetChartView.cshtml
@model SpendOMeter.ViewModels.ChartViewModel

@{
    //using System.Web.UI.DataVisualization.Charting;
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>BudgetChartView</title>
</head>
<body>
    <div>
         
        @{ 
            @Model.Chart.Write(format: "png")
            // System.Web.UI.DataVisualization.Charting chart1 = new System.Web.UI.DataVisualization.Charting.ch            
        }
    </div>
</body>
</html>

SpendOMeter/Views/Home/Index.cshtml
@model SpendOMeter.ViewModels.HomeViewModel
    <!--
<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS, and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>
        -->
<a href='@Url.Action("Index", "Payments")'>
<img src='@Url.Content("Home/BudgetChartView")' />
</a>
<!--
<img src="BudgetChartView" />    
-->
<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>ASP.NET Web API is a framework that makes it easy to build HTTP services that reach
        a broad range of clients, including browsers and mobile devices. ASP.NET Web API
        is an ideal platform for building RESTful applications on the .NET Framework.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301870">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301871">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301872">Learn more &raquo;</a></p>
    </div>
</div>