SpendOMeter/Models/PaymentViewModel.cs
using SpendOMeter.Domain;
using System.Collections.Generic;

namespace SpendOMeter.ViewModels
{
    public class PaymentViewModel
    {

    }
}

SpendOMeter/Models/PaymentsViewModel.cs
using SpendOMeter.Domain;
using System.Collections.Generic;

namespace SpendOMeter.ViewModels
{
    public class PaymentsViewModel
    {
        public IEnumerable<Payment> Paymnets { get; set; }
    }
}

SpendOMeter/Controllers/PaymentsController.cs
using SpendOMeter.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SpendOMeter.Domain;
using SpendOMeter.Repositories;

namespace SpendOMeter.Controllers
{
    public class PaymentsController : SkateBaseController
    {
        // GET: Payments
        public ActionResult Index()
        {
            PaymentsViewModel viewModel = new PaymentsViewModel();
            viewModel.Paymnets = GetPayments();
            return View(viewModel);
        }

        private IEnumerable<Payment> GetPayments()
        {
            PaymentsRepository repository = new PaymentsRepository();
            IEnumerable<Payment> payments = repository.Get();
            //List<PaymentViewModel> retVal = new List<PaymentViewModel>();
            //// Use AutoMapper
            //foreach(Payment payment in payments)
            //{

            //}
            //return retVal;
            return payments;
        }

        // GET: Payments/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Payments/Create
        public ActionResult Create()
        {
            if (Request.UrlReferrer != null)
            {
                ViewBag.ReferringUrl = Request.UrlReferrer.ToString();
            }
            RecipientsRepository repository = new RecipientsRepository();
            ViewBag.Recipients = repository.Get();
            Payment payment = new Payment();
            return View(payment);
        }

        // POST: Payments/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            DateTime date = DateTime.Now;
            decimal amount = new decimal(0.0);
            int recipientId = 0;
            string name = "";
            try
            {
                amount = GetFormValue<decimal>(collection, "amount");
                name = GetFormValue<string>(collection, "name");
                date = GetFormValue<DateTime>(collection, "date");
                recipientId = GetFormValue<int>(collection, "recipientId");
                PaymentsRepository repository = new PaymentsRepository();
                Payment payment = new Payment()
                {
                    Amount = amount,
                    Name = name,
                    Date = date,
                    RecipientId = recipientId,
                    CategoryId = 1
                };
                repository.Add(payment);
                //return SkateRedirect(collection);
                return RedirectToAction("Index");
            }
            catch(Exception ex)
            {
                throw new Exception("Failed to add payment.", ex);
                //return View();
            }
        }

        // GET: Payments/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Payments/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Payments/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Payments/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

SpendOMeter/Controllers/RecipientsController.cs
using SpendOMeter.Domain;
using SpendOMeter.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SpendOMeter.Controllers
{
    public class RecipientsController : SkateBaseController
    {
        // GET: Recipients
        public ActionResult Index()
        {
            return View();
        }

        // GET: Recipients/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Recipients/Create
        public ActionResult Create()
        {
            if (Request.UrlReferrer != null)
            {
                ViewBag.ReferringUrl = Request.UrlReferrer.ToString();
            }
            return View();
        }

        // POST: Recipients/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            string name = "";
            try
            {
                if (collection["name"] == null)
                {
                    throw new Exception("The name must be specified.");
                }
                name = collection["name"];

                RecipientsRepository repository = new RecipientsRepository();
                Recipient recipient = new Recipient()
                {
                    Name = name
                };
                repository.Add(recipient);
                return SkateRedirect(collection);
            }
            catch(Exception ex)
            {
                throw new Exception("Failed to create new Recipient.", ex);
            }
        }



        // GET: Recipients/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Recipients/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Recipients/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Recipients/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

SpendOMeter/Views/Payments/Create.cshtml
@model SpendOMeter.Domain.Payment

@{
    ViewBag.Title = "Create a new Payment";
}

<h2>CreatePaymnetView</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Payment</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
                @Html.LabelFor(model => model.RecipientId, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">

                    @Html.DropDownList("RecipientId", new SelectList(ViewBag.Recipients, "Id", "Name"))
                    <!--
        @Html.EditorFor(model => model.RecipientId, new { htmlAttributes = new { @class = "form-control" } })
           -->
                    @Html.ValidationMessageFor(model => model.RecipientId, "", new { @class = "text-danger" })
                </div>
            <div>
                <a href="@Url.Action("Create", "Recipients")" class="btn btn-warning" style="float: right;">
                    <div class="glyphicon glyphicon-plus-sign" aria-hidden="true"></div>
                </a> 
            </div>
        </div>
        @Html.Hidden("ReferringUrl", (string)ViewBag.ReferringUrl);
        
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">                
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SpendOMeter/Views/Payments/Index.cshtml
@model SpendOMeter.ViewModels.PaymentsViewModel

@{
    ViewBag.Title = "Payments";
}

<h2>Index</h2>

<a href="@Url.Action("Create", "Payments")" class="btn btn-warning" style="float: right;">
    <div class="glyphicon glyphicon-plus-sign" aria-hidden="true"></div>
</a>

@{
    ViewBag.Title = "WebGrid";
    WebGrid grid = new WebGrid(source: Model.Paymnets, columnNames: new[] { "Amount", "Date", "Id", "Recipient" });
    
    //grid.GetHtml(columns: grid.Columns(
    //    grid.Column(columnName: "Date", header: "Payment Date")
    //    ));
    //   grid.Column("Date", "Payment Date",
    //format: (item) => item.Date.ToString("MM/dd/yy"),
    //canSort: true);


}
@grid.GetHtml(columns: grid.Columns(
        grid.Column(columnName: "Amount", header: "Amount"),
        grid.Column(columnName: "Name", header: "Recipient"),
        grid.Column(columnName: "Date", header: "Date",
        format: (item) => string.Format("{0:MMM-dd-yyyy}", item.Date))
        ))